- devel/iceshelf_icefront/input_lineartrend/data.ctrl
- devel/iceshelf_icefront/input_lineartrend/data.ecco
Update the code to compute a linear trend cost. Also create a new directory called input_lineartrend to include the linear trend constraint for the melt rate. The weights for the transfer coefficients and for the melt rate costs are updated.
> Update the code to compute a linear trend cost and a few namelists

- devel/V4r5_devel/code/exf_getffields.F
Correct a few misplaced #undef with #endif in exf_getffields.F. Also, fix a couple of typos that caused new lines incorrectly being treated as a continued line to its previous line.
> Correct a few misplaced #undef with #endif and other bugs

- devel/V4r5_devel/code/exf_getffields.F
Move the pieces of code applying the zero bound to forcing outside of IF blocks testing xx_gentim2d_file. Otherwise, the zero bound would not apply to a forcing if there is no corresponding control variable.
> Apply zero forcing bound outside of IF blocks testing xx_gentim2d_file

- devel/V4r5_devel/code/SALT_PLUME_OPTIONS.h
- devel/V4r5_devel/code/SEAICE_OPTIONS.h
- devel/V4r5_devel/code/SHELFICE.h
- devel/V4r5_devel/code/seaice_growth_adx.F
- devel/V4r5_devel/code/shelfice_init_fixed.F
- devel/V4r5_devel/code/shelfice_thermodynamics.F
The pull request contains the following two changes:
1) Get rid of some recomputations in shelfice_thermodynamics.F by not calculating CURI and CURJ in shelfice_thermodynamics.F. Instead, two arrays CURI_ARR and CURJ_ARR are created and initialized with CURI and CURJ in shelfice_init_fixed.F. CURI and CURJ in shelfice_thermodynamics.F are then assigned with the corresponding CURI_ARR and CURJ_ARR.
2) Turn on two CPP options:
In SEAICE_OPTIONS.h
#define ALLOW_SEAICE_FLOODING
In SALT_PLUME_OPTIONS.h
#define SALT_PLUME_IN_LEADS
> Reduce recomputation in shelfice and turn on two CPP options

- devel/V4r5_devel/code/shelfice_solve4fluxes.F
Fix a couple of bugs in shelfice_solve4fluxes.F. The freshwater flux (fwFlux) was calculated using the same equation for three cases
1) Linear temperature through ice
2) non-linear temperature through ice and melting 
3) non-linear temperature through ice and freezing.
In the bug fix, three different equations are used for the three cases.
> Fix a couple of bugs in shelfice_solve4fluxes.F

- devel/V4r5_devel/code/cost_gencost_seaicev4.F
Rename the "beta" variable in cost_gencost_seaicev4.F to "beta_T" as "beta" has been declared in PARAMS.h for df/dy.
> Fix double declaration of beta

- devel/V4r5_devel/code/cost_gencost_seaicev4.F
The variable "beta" in cost_gencost_seaicev4.F has been already declared in PARAMS.h. This commit renames "beta" in cost_gencost_seaicev4.F to "beta_T" to fix the double-declaration" bug.
> Fix a double-declaration bug

- devel/V4r5_devel/code/ggl90_calc.F
- devel/V4r5_devel/code/gmredi_calc_tensor.F
- devel/V4r5_devel/code/gmredi_xtransport.F
- devel/V4r5_devel/code/gmredi_ytransport.F
A big fix to restore stratification inside ice cavities. The bug is related to ggl90 and gmredi code that incorrectly uses values inside ice (dry points) for some of ceiling points of ice shelves.
> Restore stratification inside ice cavities

- devel/V4r5_devel/code/shelfice_solve4fluxes.F
The variable for the velocity of meltwater flux through the boundary layer was called *w_I* and is now called *w_B*.  The reason for the change is to match the document 'the three-equation model v8' that describes the model used to calculate melting.  The document will be included in the next ecco release.
> Update shelfice_solve4fluxes to match variable names

- ECCOv4 Release 4/code/linux_amd64_ifort+mpi_ice_nas
- ECCOv4 Release 4/namelist/data.diagnostics
Updates are only for V4r4
- Add a new version (from MITgcm checkpoint 68f) of the build option file linux_amd64_ifort+mpi_ice_nas. This version drops particular module names and thus is more general.
- Make the namelist file data.diagnostics the same as data.diagnostics.monthly.inddiag.
> Add new build option file and update data.diagnostics for V4r4

- ECCOv4 Release 4/namelist/data.ctrl.restart
Add data.ctrl.restart that should be used as the data.ctrl namelist if a run is restarted from a time instant other than 01/01/1992, 12Z. The data.ctrl.restart removes control variables for initial UVTS and SSH as the control adjustments of these variables are not needed if the run does not start at 12Z, 01/01/1992.
> Add data.ctrl.restart

- devel/V4r5_devel/code/shelfice_init_fixed.F
- devel/V4r5_devel/code/shelfice_thermodynamics.F
- Fix double-counting of ice-front fluxes when adding them to ice-shelf fluxes to calculate the total.
- Limit length of some diagnostic names to 8 characters
> Fix double-counting of ice-front fluxes when calculating total fluxes

- devel/V4r5_devel/code/shelfice_thermodynamics.F
Fix the following bugs in shelfice_thermodynamics.F
1) There was a missing factor of _recip_hFacC in calculating iceFrontForcingT and iceFrontForcingS to account for volume of partial cells.
2) The four diagnostics 'SHIForcT', 'SHIForcS', 'ICFForcT', and 'ICFForcS' were having incorrect units (in Wm/m^2 and gm/m^2/s for temperature and salinity forcing). The correct units should be W/m^2 and g/m^2/s. Local temporary arrays are now used to output the four diagnostics with the correct units.
> Fix a couple of minor bugs in shelfice_thermodynamics.F

- devel/V4r5_devel/README
- devel/V4r5_devel/code/CPP_OPTIONS.h
- devel/V4r5_devel/code/MITgcm_codebase
- devel/V4r5_devel/code/initialise_varia.F
- devel/V4r5_devel/code/shelfice_solve4fluxes.F
- devel/V4r5_devel/code/shelfice_thermodynamics.F
Bring codebase from 68d to 68g (so TS budgets can be closed because of bug fixes in pkg/gmredi (see MITgcm Pull Request [#593](https://github.com/MITgcm/MITgcm/pull/593)).
Reformulate heat flux due to ice shelf/front melt. This would result in having better closure of heat budget. 
Calculate phiHydLow during initialization by default so the first time record of OBP would be correct. Otherwise, ecco_phys.F would use phiHydLow=0 when calculating the first time record of OBP.
> A few updates

- ECCOv4 Release 4/flux-forced/namelist/data.ecco
Fix a typo in data.ecco of the flux-forced version of V4r4
> Fix a typo in data.ecco of flux-forced V4r4

- ECCOv4 Release 4/flux-forced/code/ecco_phys.F
When calculating fields for m_boxmean and/or m_horflux_vol, make weighted variable strictly be weight times model variable without including area, volume or any other factor.
> Exclude area or volume when calculating weights for boxmean costs

- ECCOv4 Release 4/namelist/data.ctrl.unpack.inclatmctrl
- ECCOv4 Release 4/namelist/data.ctrl_itXX.inclatmctrl
Add example data.ctrl files that include atmospheric controls:
data.ctrl.unpack.inclatmctrl for starting from ecco_ctrl file 
data.ctrl_itXX.inclatmctrl for starting from xx files 
To use either file, one needs to copy the file to data.ctrl.
> Add data.ctrl having atmospheric controls

- ECCOv4 Release 4/flux-forced/doc/README_fluxforced.md
Add a Markdown version of the document about the configuration of the flux-forced version of ECCO V4r4. The PDF version of the document will be removed in a different commit.
> Convert fluxforced pdf2md

- ECCOv4 Release 5/code/ecco_phys.F
- ECCOv4 Release 5/namelist/data.diagnostics
- ECCOv4 Release 5/namelist/data.diagnostics.daily.inddiag
- ECCOv4 Release 5/namelist/data.diagnostics.monthly.inddiag
1. Name list change: Output OBP and OBPGMAP in double precision 
2. Code change: Remove masking applied to SSH and SSHNOIBC. Previously, the first-level dry/wet masking (maskC at k=1) was used to mask output SSH and SSHNOIBC. This change makes the diagnostic outputs SSH and SSHNOIBC have non-zero values under ice-shelves.
> Updates for Release 5 

- ECCOv4 Release 4/flux-forced/doc/README_offline_ptracer.md
- ECCOv4 Release 4/flux-forced/namelist_offline_ptracer/data.ptracers
Initialize offline tracer using a pickup file instead of specifying PTRACERS_initialFile in data.ptracers. See ECCO-v4-Configurations/ECCOv4 Release 4/flux-forced/doc/README_offline_ptracer.md for details. Using a pickup file is more flexible than specifying PTRACERS_initialFile in data.ptracers.
> Initialize offline tracer using a pickup file

- ECCOv4 Release 4/flux-forced/scripts/rename_offline_adj_diags_fn.sh
When 'YES' is provided as an argument, rename_offline_adj_diags_fn.sh skips the step of asking the user to type in 'YES' for confirmation.
Also, add feature to count and display the number of files named.
> Allow rename_offline_adj_diags_fn.sh to take YES as an argument

- ECCOv4 Release 4/flux-forced/code/code_ad_diff.list
- ECCOv4 Release 4/flux-forced/code/ctrl_cost_gen.F
- ECCOv4 Release 4/flux-forced/code/ctrl_get_gen.F
- ECCOv4 Release 4/flux-forced/code/ctrl_init.F
- ECCOv4 Release 4/flux-forced/code/ctrl_map_ini_gentim2d.F
- ECCOv4 Release 4/flux-forced/code/ecco_init_varia.F
- ECCOv4 Release 4/flux-forced/code/ecco_phys.F
- ECCOv4 Release 4/flux-forced/code/ecco_read_pickup.F
- ECCOv4 Release 4/flux-forced/code/ecco_write_pickup.F
- ECCOv4 Release 4/flux-forced/code/packages_write_pickup.F
- ECCOv4 Release 4/flux-forced/code/the_model_main.F
This pull request enables ECCO V4r4's flux-forced model to restart from a set of pickups, even when the control package is active. Such capability was not available in the V4r4 code base, specifically in MITgcm checkpoint66g, although it has been implemented in more recent MITgcm releases. 
The pickup files are `pickup.0123456789.data`, `pickup_ggl90.0123456789.data`, `pickup_ecco.0123456789.data`, as well as their corresponding meta files (replace the 10-digit number 0123456789 with the restart time-step number). These pickup files can be generated by running the model from `nIter0`=1. In particular, the file `pickup_ecco.0123456789.data` is a new kind of pickup file that was not part of the original V4r4 setup's output. It contains the initial (at `nIter0`=1) global ocean mean volume …
> Allow model to restart from pickups

- ECCOv4 Release 4/flux-forced/code/ecco_check.F
When checking if gencost_barfile is equal to m_horflux_vol, the length of the filename of gencost_barfile should be 1:13, not 1:14.
> Fix wrong filename length for m_horflux_vol

- ECCOv4 Release 4/flux-forced/namelist/data.diffkr_total
- ECCOv4 Release 4/flux-forced/namelist/data.gmredi_total
Add more namelist files that specify the filenames of ECCO V4r4's total DiffKr, KapGM, and KapRedi fields, with their control adjustments folded in.
> Add more namelist files for V4r4 flux-forced

- ECCOv4 Release 4/flux-forced/scripts/reverseintime_all.sh
In reverseintime_all.sh, change
sh -x ../../reverseintime.sh ${var1} ${dirin}  0 ${maxtimestep}
to
bash -x ../../reverseintime.sh ${var1} ${dirin}  0 ${maxtimestep}
Command 'sh' will ignore the shebang and could run the script in a shell other than bash.
> Change sh to bash in reverseintime_all.sh
