README.md
Create a directory called devel to host pieces of code that are useful, but still under development and not checked into the main MITgcm repository yet.
=> Create directory devel for pieces of code under development

devel/README, devel/iceshelf_icefront/README
Add the merged ice-shelf and ice-front code.
=> Add the merged ice-shelf and ice-front code

devel/README
Fix a small formatting bug in README.
=> fix a small formatting bug

devel/fluxforced/README.md, devel/fluxforced/input_fluxforced/data.exf_sflux_excl_runoff
update data.exf for flux_forced runs.
=> update data.exf for flux_forced runs

devel/fluxforced/input_fluxforced/data.exf, devel/fluxforced/input_fluxforced/data.exf_sflux_excl_runoff, devel/fluxforced/tools_generate_forcing/cat_exf2yearly_fromavg.sh, devel/fluxforced/tools_generate_forcing/cat_exf2yearly_fromavg_all.sh
Change the forcing start time from 9Z to 3Z and update the aggregation script accordingly
=> Change forcing start time from 9Z to 3Z 

devel/fluxforced/code_fluxforced_v4r3/AUTODIFF.h
Add AUTODIFF.h with increased NEXF1
=> Add AUTODIFF.h with increased NEXF1

ECCOv4 Release 4/README, README.md
First commit of ECCO Version 4 Release 4
=> First commit of ECCO Version 4 Release 4

ECCOv4 Release 4/flux-forced/code/cost_gencost_boxmean.F
Replace a symbol link with the actual file cost_gencost_boxmean.F.
=> Replace a symbol link with the actual file

devel/seaice_adjoint/code/seaice_growth_adx.F
Simply split a loop to remove RECOMP.
=> Fix seaice growth adx recomps

ECCOv4 Release 4/flux-forced/code/cost_gencost_boxmean.F, ECCOv4 Release 4/flux-forced/code/ecco_phys.F
Move area/volume weighting back from cost_gencost_boxmean.F to ecco_phys.F.
=> Move area/volume weighting back to ecco_phys.F

ECCOv4 Release 4/flux-forced/namelist/data.ecco
=> Update data.ecco one more time

ECCOv4 Release 4/code/mdsio_read_meta.F
=> Mdsio read fix try 2

devel/V4r5_devel/code/EXF_OPTIONS.h, devel/V4r5_devel/code/exf_getffields.F
Adds zero bounds to the following adjusted fields
#ifdef EXF_ZERO_BOUND_AQH 
#ifdef EXF_ZERO_BOUND_PRECIP
#ifdef EXF_ZERO_BOUND_SWDOWN
#ifdef EXF_ZERO_BOUND_LWDOWN
#ifdef EXF_ZERO_BOUND_RUNOFF
max(field, 0. _0)
All of these fields have physical values of  0 >= FIELD
=> Bound certain adjusted controls

devel/V4r5_devel/code/exf_getffields.F
only adjust SW if the prescribed SW > 0.
If SW = 0 then leave it alone!
=> At night there should be no need for sunglasses

ECCOv4 Release 4/code/seaice_diagnostics_init.F, ECCOv4 Release 4/code/seaice_growth.F, ECCOv4 Release 4/namelist/data.diagnostics.daily.inddiag, ECCOv4 Release 4/namelist/data.diagnostics.monthly.inddiag
=> Output a few more diagnostics

ECCOv4 Release 4/namelist/data.diagnostics.gcmfaces
Fix a minor bug in data.diagnostics.gcmfaces.
=> Fix a minor bug

ECCOv4 Release 4/scripts/example_autoiter.csh
Add an example run script that automates the iterations by the following steps; 
1) do optimization to generate ecco_ctrl for iteration n
2) conduct iteration n (forward and adjoint)
3) repeat 1) for iteration n+1
=> Add an example run script 

devel/V4r5_devel/code/ggl90_calc.F, devel/V4r5_devel/code/gmredi_calc_tensor.F, devel/V4r5_devel/code/gmredi_xtransport.F, devel/V4r5_devel/code/gmredi_ytransport.F
A big fix to restore stratification inside ice cavities. The bug is related to ggl90 and gmredi code that uses values inside ice (dry points) for some of ceiling points of ice shelves.
=> Restore stratification inside ice cavities

devel/V4r5_devel/README
Update README to reflect V4r5 codebase change from 67l to 68d
=> Update README to reflect V4r5 codebase change

devel/V4r5_devel/input/data, devel/V4r5_devel/input/data.ctrl.unpack, devel/V4r5_devel/input/data.ctrl_itXX, devel/V4r5_devel/input/data.diagnostics, devel/V4r5_devel/input/data.diagnostics.daily.inddiag, devel/V4r5_devel/input/data.diagnostics.monthly.inddiag, devel/V4r5_devel/input/data.ecco, devel/V4r5_devel/input/data.optim
The following two data.diagnostics save one field per file: 
1) data.diagnostics.daily.inddiag for daily fields, including daily means and snapshots with daily interval;
2) data.diagnostics.monthly.inddiag for monthly mean fields.
=> Add versions of data.diagnostics

devel/V4r5_devel/input/data.optim
Update optimcycle in V4r5's data.optim from 129 to 180.
=> Update optimcycle from 129 to 180

devel/V4r5_devel/input/data.diagnostics
Update data.diagnostics to output GGL90-related diagnostics and 3d velocity
=> Add extra diagnostics to data.diagnostics

ECCOv4 Release 5/namelist/data.diagnostics_grouped, ECCOv4 Release 5/namelist/data.diagnostics_single
Add data.diagnostics_single that outputs monthly and daily means, snapshots at daily intervals. Each file has one field only. 
Add a new group of sea-ice thermo budget terms in data.diagnostics_grouped
=> Add data.diagnostics_single and update data.diagnostics_grouped 

ECCOv4 Release 4/namelist/data.ctrl.iter0, ECCOv4 Release 4/namelist/data.exf.iter0, ECCOv4 Release 4/namelist/data.gmredi.iter0, ECCOv4 Release 4/namelist/data.iter0
Add a few namelist files that are suitable for iteration 0. Iteration 0 is a run that is forced by first-guess forcing, initial conditions, and mixing parameters.
=> Add namelists for iteration 0 (forced by fist guess)

ECCOv4 Release 4/flux-forced/doc/README_offline_ptracer.md
Minor change of a README file to reflect the replacement of the PDF version of the flux-forced configuration document by a Markdown version.
=> Minor change of a README file

ECCOv4 Release 5/namelist/data.ctrl.noatmctrl, ECCOv4 Release 5/namelist/data.exf.combforc
Add new name list files to run V4r5 using total forcing that has control adjustments folded in.
=> Add new name list files to run V4r5 using total forcing (first guess + control)

ECCOv4 Release 4/namelist_adjsen/data, ECCOv4 Release 4/namelist_adjsen/data.ctrl, ECCOv4 Release 4/namelist_adjsen/data.ecco, ECCOv4 Release 4/namelist_adjsen/data.pkg
Create name lists to calculate adjoint sensitivity for a simple cost
=> First commit to calculate adjoint sensitivity for a simple cost

ECCOv4 Release 4/scripts/pbs_v4r4.adjsen.simplecost.csh
Add an example run script for calculating adjoint sensitivity of a simple cost
=> Add an example run script for calculating adjoint sensitivity

ECCOv4 Release 4/Docker/Dockerfile, ECCOv4 Release 4/Docker/LICENSE, ECCOv4 Release 4/Docker/README.md, ECCOv4 Release 4/Docker/src/SIZE.h_12, ECCOv4 Release 4/Docker/src/SIZE.h_13, ECCOv4 Release 4/Docker/src/SIZE.h_16, ECCOv4 Release 4/Docker/src/SIZE.h_24, ECCOv4 Release 4/Docker/src/SIZE.h_48, ECCOv4 Release 4/Docker/src/SIZE.h_96, ECCOv4 Release 4/Docker/src/build_MITgcm_ECCO.sh, ECCOv4 Release 4/Docker/src/get_MITgcm_ECCO.sh, ECCOv4 Release 4/Docker/src/linux_amd64_gfortran
Moved Docker instructions for V4r4 in to ecco-v4-configurations
=> Moved Docker instructions for V4r4 in to ecco-v4-configurations

ECCOv4 Release 4/flux-forced/code/ECCO_OPTIONS.h, ECCOv4 Release 4/flux-forced/code/cost_gencost_all.F, ECCOv4 Release 4/flux-forced/code/ecco_readparms.F
Restrict the use of EMU tools for optimization
=> Restrict the use of EMU tools for optimization

ECCOv4 Release 4/flux-forced/scripts/rename_offline_adj_diags_fn.sh
Add a bash script to rename diagnostic output filenames of an offline adjoint tracer run
=> Add a bash script to rename diagnostic output filenames 
